CREATE DATABASE JOURNAL;

CREATE TABLE ENTRY (
    ENTRYID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(256),
    ENTRYDATE date,
    KINID int,
    EXPERIENCEID int,


    PRIMARY KEY (ENTRYID)
    FOREIGN KEY (KINID)
    FOREIGN KEY (EXPERIENCEID)
);


CREATE TABLE KIN (
    KINID int NOT NULL AUTO_INCREMENT,
    NAME varchar(256),
    SPECIES varchar(256),
    DESCRIPTION varchar(500),

    PRIMARY KEY (KINID)
);




CREATE TABLE EXPERIENCE (
    EXPERIENCEID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(256),
    DESCRIPTION varchar(500)

    PRIMARY KEY (EXPERIENCEID)
);



